ECommerce/Components/NavViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ECommerce.Components
{
    public class NavViewComponent: ViewComponent
    {
        private IProductRepository _repository;

        public NavViewComponent(IProductRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            return View(_repository.Products.Select(p => p.Category).Distinct().OrderBy(s =>s));
        }

    }
}

ECommerce/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link asp-href-include="/lib/bootstrap/dist/css/*.min.css" rel="stylesheet" />
    <style>   .card-deck {margin-top: 150px}     .card-img-top {  height: 200px;background: gray
        } .navvc{ margin-top:50px} .categories{margin-top:100px} .mid{ height: 150px} 
 
       
        </style>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
<div>
    <div class="navbar bg-dark">
        <a class="navbar-brand text-white" asp-route="/">General Store</a>
    </div>
    <div class=" row m-1 p-1">
        <div class="categories col-3">@await Component.InvokeAsync("Nav")</div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</div>
</body>
</html>