ECommerce/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECommerce.Models.ViewModels;

namespace ECommerce.Models
{

    public class Order
    {
        public int OrderId { get; set; }
        public int AddressId { get; set; }
        public Address ShippingInfo { get; set; }
        
        public List<LineItem> OrderItems { get; set; } = new List<LineItem>();
    }
}

ECommerce/Models/ViewModels/PaymentInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Models.ViewModels
{
    public class PaymentInfoViewModel
    {
        [Display(Name="Payment Method")]
        [Required(ErrorMessage = "Select a payment method")]
        public PaymentMethods PaymentMethod { get; set; }

        [RegularExpression(@"^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$", ErrorMessage = "Credit Card number is not valid.")]
        public string CardNumber { get; set; }

        [Display(GroupName= "Expiration Date")]
        [Required(ErrorMessage = "Requiredm.")]
        [Range(1,13, ErrorMessage = "Must be 1-12")]
        public int? Month { get; set; }

        [Required(ErrorMessage = "Requiredy.")]
        public int? Year { get; set; }

        [Display(GroupName = "Billing Name and Address")]
        public AddressViewModel BillingAddress { get; set; }
    }


    public enum PaymentMethods
    {
        Discover,
        [Display(Name = "Master Card")]MasterCard,
        Visa,
    }
}

ECommerce/Models/ViewModels/ReviewOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.Models.ViewModels
{
    public class ReviewOrderViewModel
    {
        public Cart Cart { get; set; }
        public AddressViewModel ShipInfo { get; set; }
    }
}

ECommerce/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECommerce.Infrastructure;
using ECommerce.Models;
using ECommerce.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SpaServices.Prerendering;
using Microsoft.EntityFrameworkCore;
using StackExchange.Redis;
using Order = ECommerce.Models.Order;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ECommerce.Controllers
{
    public class CheckoutController : Controller
    {
        private AppDbContext _context;

        public CheckoutController(AppDbContext context)
        {
            _context = context;
        }


        [HttpGet]
        public IActionResult ShipInfo()
        {
            var shipInfo = HttpContext.Session.GetJson<AddressViewModel>("ShipInfo") ?? new AddressViewModel();
            return View("NewAddress", shipInfo);
        }

        [HttpPost]
        public IActionResult ShipInfo(AddressViewModel shipInfo)
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session.SetJson("ShipInfo", shipInfo);
                return RedirectToAction("PaymentInfo");
            }
            return View("NewAddress", shipInfo);
        }

        public IActionResult EditShipInfo()
        {
            var shipInfo = HttpContext.Session.GetJson<AddressViewModel>("ShipInfo");
            return View("NewAddress", shipInfo);
        }

        [HttpGet]
        public IActionResult PaymentInfo()
        {
            var payInfo = HttpContext.Session.GetJson<PaymentInfoViewModel>("PaymentInfo") ?? new PaymentInfoViewModel();
            payInfo.CardNumber = "";
            return View(payInfo);
        }

        [HttpPost]
        public IActionResult PaymentInfo(PaymentInfoViewModel payInfo)
        { 
            if (ModelState.IsValid)
            {
                HttpContext.Session.SetJson("PaymentInfo", payInfo);
                return RedirectToAction("ReviewOrder");
            }
            return View();
        }

        [HttpGet]
        public IActionResult ReviewOrder()
        {
            var cartContents = HttpContext.Session.GetJson<Cart>("Cart");
            if (cartContents == null)
            {
                return RedirectToAction("ViewCart", "Cart");}

            var shipInfo = HttpContext.Session.GetJson<AddressViewModel>("ShipInfo");
            if (shipInfo == null)
            {
                return RedirectToAction("ShipInfo");}
            return View( new ReviewOrderViewModel(){Cart = cartContents, ShipInfo = shipInfo});
        }

        [HttpPost]
        public IActionResult SubmitOrder()
        {
            var cartContents = HttpContext.Session.GetJson<Cart>("Cart");
            var shipInfo = HttpContext.Session.GetJson<AddressViewModel>("ShipInfo");
            var address = new Address()
            {
                FirstName = shipInfo.FirstName,
                LastName = shipInfo.LastName,
                AddressLine1 = shipInfo.AddressLine1,
                AddressLine2 = shipInfo.AddressLine1,
                City = shipInfo.City,
                State = shipInfo.State,
                Zipcode = (int)shipInfo.Zipcode,
                Phone = (long)shipInfo.Phone
            };
            _context.Addresses.Add(address);
            var items = new List<LineItem>();
            items.AddRange(cartContents.LineItems);
            var newOrder = new Order()
            {
                ShippingInfo = address,
                OrderItems = items,
            };
            _context.AttachRange(newOrder.OrderItems);
            _context.Orders.Add(newOrder);
            _context.SaveChanges();
            var orderId = newOrder.OrderId;
            HttpContext.Session.Clear();
            return View("OrderConfirmation");
        }
        //check if orders saved to DB
        public IActionResult GetOrder()
        {
           var order= _context.Orders.Include(p => p.OrderItems).FirstOrDefault();
            return View("Order", order);
        }

    }
}

ECommerce/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECommerce.Models;
using ECommerce.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace ECommerce.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _repository;
        public int PageSize = 4;

        public ProductController(IProductRepository repository)
        {
            _repository = repository;
        }

        public IActionResult ProductDirectory(string category, int pageNum = 1)
        {
            var dataset = _repository.Products.Where(p=> category == null || p.Category == category);
            var numpages = Math.Ceiling((decimal)dataset.Count() / PageSize);
             var products = dataset.OrderBy(p => p.ProductId).Skip((pageNum - 1) * PageSize).Take(PageSize);
            
            return View(new ProductViewModel
            {
                Products = products,
                NumPages = (int)numpages
            });

        }
        
    }


}

ECommerce/Views/Checkout/NewAddress.cshtml
@model AddressViewModel

@{
    ViewData["Title"] = "Checkout: Ship To";
}
@{
Layout = "_Layout";
}


<h4>Contact and  Shipping Information</h4>

<h6>Enter your name and and contact information.</h6>
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShipInfo" asp-controller="Checkout">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>


            <h6>Enter your shipping address.</h6>
            <div class="form-group">
                <label asp-for="AddressLine1" class="control-label"></label>
                <input asp-for="AddressLine1" class="form-control" />
                <span asp-validation-for="AddressLine1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressLine2" class="control-label"></label>
                <input asp-for="AddressLine2" class="form-control" />
                <span asp-validation-for="AddressLine2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input maxlength="5" asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Continue Checkout" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ProductDirectory" asp-controller="Product">Back to Store</a>
</div>

ECommerce/Views/Checkout/Order.cshtml
@model Order

@Model.OrderId
@foreach (var p in Model.OrderItems)
{
    <p>@p.Item.Name</p>
    <p>@p.Item.Price</p>
}

ECommerce/Views/Checkout/OrderConfirmation.cshtml
<h1>Thank you for your order!</h1>

ECommerce/Views/Checkout/PaymentInfo.cshtml
@model PaymentInfoViewModel

<h6>Enter your payment information.</h6>
<div class="row">
    <div class="col-md-4">
        <form asp-action="PaymentInfo" asp-controller="Checkout">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="PaymentMethod"></label>
                <select class="form-control" asp-for="PaymentMethod" asp-items="@new SelectList(Enum.GetNames(typeof(PaymentMethods)))">
                    <option selected disabled>Select Payment Method</option>

                </select>
                <span asp-validation-for="PaymentMethod" class="text-danger"></span>

                <div class="form-group">
                    <label asp-for="CardNumber"></label>
                    <input class="form-control"asp-for="CardNumber" />
                    <span asp-validation-for="CardNumber" class="text-danger"></span>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Month"></label>
                        <input placeholder="MM"class="form-control" asp-for="Month" />
                        <span asp-validation-for="Month" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <label asp-for="Year"></label>
                        <input placeholder="YY" class="form-control" asp-for="Year" />
                        <span asp-validation-for="Year" class="text-danger"></span>
                    </div>

                </div>



            </div>
           
            <div class="form-group">
                <label asp-for="BillingAddress.FirstName" class="control-label"></label>
                <input asp-for="BillingAddress.FirstName" class="form-control" />
                <span asp-validation-for="BillingAddress.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress.LastName" class="control-label"></label>
                <input asp-for="BillingAddress.LastName" class="form-control" />
                <span asp-validation-for="BillingAddress.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress.Phone" class="control-label"></label>
                <input asp-for="BillingAddress.Phone" class="form-control" />
                <span asp-validation-for="BillingAddress.Phone" class="text-danger"></span>
            </div>


            <h6>Enter your billing Address.</h6>
            <div class="form-group">
                <label asp-for="BillingAddress.AddressLine1" class="control-label"></label>
                <input asp-for="BillingAddress.AddressLine1" class="form-control" />
                <span asp-validation-for="BillingAddress.AddressLine1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress.AddressLine2" class="control-label"></label>
                <input asp-for="BillingAddress.AddressLine2" class="form-control" />
                <span asp-validation-for="BillingAddress.AddressLine2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress.City" class="control-label"></label>
                <input asp-for="BillingAddress.City" class="form-control" />
                <span asp-validation-for="BillingAddress.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress.State" class="control-label">State:</label>
                <input asp-for="BillingAddress.State" class="form-control" />
                <span asp-validation-for="BillingAddress.State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress.Zipcode" class="control-label">Zipcode:</label>
                <input asp-for="BillingAddress.Zipcode" class="form-control" />
                <span asp-validation-for="BillingAddress.Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Continue Checkout" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

ECommerce/Views/Checkout/ReviewOrder.cshtml
@using System.Collections
@model ReviewOrderViewModel
    
<h3 class="edit">Cart Contents:</h3> <a asp-action="ViewCart" asp-controller="cart" type="button" class="edit btn btn-sm">Edit Cart Contents</a>
<table class="table table-sm w-50">
@if (Model.Cart.LineItems.Count < 1)
{
    <tr><td>Your Cart is Empty</td></tr>
}
else
{
foreach(var p in Model.Cart.LineItems)
 {
     <tr>
         <td>@p.Item.Name</td>
         <td>@p.Quantity</td>
         <td>@p.Item.Price.ToString("C")</td>
     </tr>
 }
    <tr class="font-weight-bold"><td></td><td>Subtotal</td><td>@Model.Cart.LineItems.Sum(a => a.Item.Price).ToString("C")</td></tr>
}
</table>


<h3 class="edit">Ship To:</h3> <a asp-action="EditShipInfo" type="button" class=" edit btn btn-sm">Edit Shipping Info</a>
<h6>@Model.ShipInfo.FirstName @Model.ShipInfo.LastName</h6> 
<p>@Model.ShipInfo.AddressLine1</p>
<p>@Model.ShipInfo.AddressLine2</p>
<p>@Model.ShipInfo.City, @Model.ShipInfo.State @Model.ShipInfo.Zipcode</p>

<p>@Model.ShipInfo.Phone.Value.ToString("###-###-####")</p>

<form asp-action="SubmitOrder" asp-controller="Checkout" method="post">
    <input type="submit" class="btn btn-primary" value="Complete Order"/>
</form>

ECommerce/Views/Checkout/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link asp-href-include="/lib/bootstrap/dist/css/*.min.css" rel="stylesheet" />
    <style>   .card-deck {margin-top: 150px}     .card-img-top {  height: 200px;background: gray
        } .navvc{ margin-top:50px} .categories{margin-top:100px} .mid{ height: 150px}
        .edit {
            display: inline-block
        } .edit+.btn { margin-left:50px}
 
       
        </style>
</head>
<body>
<div>
    <div class="navbar bg-dark">
        <a class="navbar-brand text-white" asp-action="#">General Store</a>
    </div>
    <div class=" row m-1 p-1">
        
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</div>
</body>
</html>